name: Test, typecheck, and lint

on: push

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run test
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Typecheck
        run: npm run check
