# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test (and deploy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - name: Install node modules
      run: npm ci
    - name: Run tests
      run: npm test
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/main' # If this is running on the "main" branch
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist/ # The folder the action should deploy.
